class TimelineController < ApplicationController

  # User must be logged in to access anything
  before_filter :authenticate_user!
  
  def index
  	@user = current_user
  	@books = ['Genesis',
              'Exodus',
              'Leviticus',
              'Numbers',
              'Deuteronomy',
              'Joshua',
			        'Judges',
              'Ruth',
              '1 Samuel',
              '2 Samuel',
              '1 Kings',
              '2 Kings',
              '1 Chronicles',
			       '2 Chronicles',
              'Ezra',
              'Nehemiah',
              'Esther',
              'Job',
              'Psalms',
              'Proverbs',
			        'Ecclesiastes',
              'Song of Songs',
              'Isaiah',
              'Jeremiah',
              'Lamentations',
              'Ezekiel',
              'Daniel',
              'Hosea',
              'Joel',
              'Amos',
              'Obadiah',
              'Jonah',
              'Micah',
              'Nahum',
              'Habakkuk',
              'Zephaniah',
              'Haggai',
              'Zechariah',
              'Malachi',
              'Matthew',
              'Mark',
              'Luke',
              'John',
              'Acts',
              'Romans',
              '1 Corinthians',
              '2 Corinthians',
              'Galatians',
              'Ephesians',
              'Philippians',
              'Colossians',
              '1 Thessalonians',
              '2 Thessalonians',
              '1 Timothy',
              '2 Timothy',
              'Titus',
              'Philemon',
              'Hebrews',
              'James',
              '1 Peter',
              '2 Peter',
              '1 John',
              '2 John',
              '3 John',
              'Jude',
              'Revelation']
  end

  def edit
  	@user = current_user

  	@book_list = [{:name => "Genesis", :class => "brick size12", :position => ''},
                	{:name => "Exodus", :class => "brick size12", :position => ''},
                  {:name => "Leviticus", :class => "brick size12", :position => ''},
                	{:name => "Numbers", :class => "brick size12", :position => ''},
                	{:name => "Deuteronomy", :class => "brick size12", :position => ''},
                	{:name => "Joshua", :class => "brick size12", :position => ''},
                	{:name => "Judges", :class => "brick size12", :position => ''},
                  {:name => 'Ruth', :class => 'brick size12', :position => ''},
                  {:name => '1 Samuel', :class => 'brick size12', :position => ''},
                  {:name => '2 Samuel', :class => 'brick size12', :position => ''},
                  {:name => '1 Kings', :class => 'brick size12', :position => ''},
                  {:name => '2 Kings', :class => 'brick size12', :position => ''},
                  {:name => '1 Chronicles', :class => 'brick size12', :position => ''},
                  {:name => '2 Chronicles', :class => 'brick size12', :position => ''},
                  {:name => 'Ezra', :class => 'brick size12', :position => ''},
                  {:name => 'Nehemiah', :class => 'brick size12', :position => ''},
                  {:name => 'Esther', :class => 'brick size12', :position => ''},
                  {:name => 'Job', :class => 'brick size12', :position => ''},
                  {:name => 'Psalms', :class => 'brick size12', :position => ''},
                  {:name => 'Proverbs', :class => 'brick size12', :position => ''},
                  {:name => 'Ecclesiastes', :class => 'brick size12', :position => ''},
                  {:name => 'Song of Songs', :class => 'brick size12', :position => ''},
                  {:name => 'Isaiah', :class => 'brick size12', :position => ''},
                  {:name => 'Jeremiah', :class => 'brick size12', :position => ''},
                  {:name => 'Lamentations', :class => 'brick size12', :position => ''},
                  {:name => 'Ezekiel', :class => 'brick size12', :position => ''},
                  {:name => 'Daniel', :class => 'brick size12', :position => ''},
                  {:name => 'Hosea', :class => 'brick size12', :position => ''},
                  {:name => 'Joel', :class => 'brick size12', :position => ''},
                  {:name => 'Amos', :class => 'brick size12', :position => ''},
                  {:name => 'Obadiah', :class => 'brick size12', :position => ''},
                  {:name => 'Jonah', :class => 'brick size12', :position => ''},
                  {:name => 'Micah', :class => 'brick size12', :position => ''},
                  {:name => 'Nahum', :class => 'brick size12', :position => ''},
                  {:name => 'Habakkuk', :class => 'brick size12', :position => ''},
                  {:name => 'Zephaniah', :class => 'brick size12', :position => ''},
                  {:name => 'Haggai', :class => 'brick size12', :position => ''},
                  {:name => 'Zechariah', :class => 'brick size12', :position => ''},
                  {:name => 'Malachi', :class => 'brick size12', :position => ''},
                  {:name => 'Matthew', :class => 'brick size12', :position => ''},
                  {:name => 'Mark', :class => 'brick size12', :position => ''},
                  {:name => 'Luke', :class => 'brick size12', :position => ''},
                  {:name => 'John', :class => 'brick size12', :position => ''},
                  {:name => 'Acts', :class => 'brick size12', :position => ''},
                  {:name => 'Romans', :class => 'brick size12', :position => ''},
                  {:name => '1 Corinthians', :class => 'brick size12', :position => ''},
                  {:name => '2 Corinthians', :class => 'brick size12', :position => ''},
                  {:name => 'Galatians', :class => 'brick size12', :position => ''},
                  {:name => 'Ephesians', :class => 'brick size12', :position => ''},
                  {:name => 'Philippians', :class => 'brick size12', :position => ''},
                  {:name => 'Colossians', :class => 'brick size12', :position => ''},
                  {:name => '1 Thessalonians', :class => 'brick size12', :position => ''},
                  {:name => '2 Thessalonians', :class => 'brick size12', :position => ''},
                  {:name => '1 Timothy', :class => 'brick size12', :position => ''},
                  {:name => '2 Timothy', :class => 'brick size12', :position => ''},
                  {:name => 'Titus', :class => 'brick size12', :position => ''},
                  {:name => 'Philemon', :class => 'brick size12', :position => ''},
                  {:name => 'Hebrews', :class => 'brick size12', :position => ''},
                  {:name => 'James', :class => 'brick size12', :position => ''},
                  {:name => '1 Peter', :class => 'brick size12', :position => ''},
                  {:name => '2 Peter', :class => 'brick size12', :position => ''},
                  {:name => '1 John', :class => 'brick size12', :position => ''},
                  {:name => '2 John', :class => 'brick size12', :position => ''},
                  {:name => '3 John', :class => 'brick size12', :position => ''},
                  {:name => 'Jude', :class => 'brick size12', :position => ''},
                  {:name => 'Revelation', :class => 'brick size12', :position => ''}]

  	
  end

end
